name: Update mods.d.tar.gz

on:
  push:
    branches: 
      - master
    paths:
      - 'andbible/mods.d/*'

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Tar mods.d
      run: |
        cd andbible
        tar cvfz mods.d.tar.gz mods.d
        git config user.email "ci@andbible.github.io"
        git config user.name "Auto CI"
        git add mods.d.tar.gz
        git commit -m "Auto-updated compressed mods configs" || echo "No changes to commit"
        git push -v origin master
